In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
%pylab inline
import scipy.io as sci

Populating the interactive namespace from numpy and matplotlib


C:\Users\Vikrant\Anaconda3\lib\site-packages\IPython\core\magics\pylab.py:160: UserWarning: pylab import has clobbered these variables: ['sci']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [3]:
#taking data and making matrix s:

In [4]:
from numpy import*
from scipy.linalg import *

mat = sci.loadmat('C:/Users/Vikrant/Desktop/NITK/given_data.mat')
mat

{'__header__': b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Fri May 25 22:09:57 2018',
 '__version__': '1.0',
 '__globals__': [],
 'total_samples_new': array([[0.4337, 0.4416, 0.4787, ..., 0.279 , 0.2792, 0.2691],
        [0.3816, 0.3888, 0.4266, ..., 0.2588, 0.2667, 0.2577],
        [0.3948, 0.3883, 0.421 , ..., 0.2602, 0.2545, 0.2521],
        ...,
        [0.2313, 0.2356, 0.2529, ..., 0.2479, 0.2361, 0.242 ],
        [0.2313, 0.2356, 0.2529, ..., 0.2468, 0.2344, 0.2403],
        [0.1949, 0.1884, 0.197 , ..., 0.2588, 0.2541, 0.2602]])}

In [5]:

S = matrix(mat['total_samples_new'])
S

matrix([[0.4337, 0.4416, 0.4787, ..., 0.279 , 0.2792, 0.2691],
        [0.3816, 0.3888, 0.4266, ..., 0.2588, 0.2667, 0.2577],
        [0.3948, 0.3883, 0.421 , ..., 0.2602, 0.2545, 0.2521],
        ...,
        [0.2313, 0.2356, 0.2529, ..., 0.2479, 0.2361, 0.242 ],
        [0.2313, 0.2356, 0.2529, ..., 0.2468, 0.2344, 0.2403],
        [0.1949, 0.1884, 0.197 , ..., 0.2588, 0.2541, 0.2602]])

In [6]:
T = np.transpose(S)
T

matrix([[0.4337, 0.3816, 0.3948, ..., 0.2313, 0.2313, 0.1949],
        [0.4416, 0.3888, 0.3883, ..., 0.2356, 0.2356, 0.1884],
        [0.4787, 0.4266, 0.421 , ..., 0.2529, 0.2529, 0.197 ],
        ...,
        [0.279 , 0.2588, 0.2602, ..., 0.2479, 0.2468, 0.2588],
        [0.2792, 0.2667, 0.2545, ..., 0.2361, 0.2344, 0.2541],
        [0.2691, 0.2577, 0.2521, ..., 0.242 , 0.2403, 0.2602]])

In [7]:
#getting Correlation matrix C from spectral matrix S

In [8]:
C = T * S
C

matrix([[ 92.45696969,  94.25216265, 102.17370333, ...,  88.40366275,
          88.81800922,  87.41167664],
        [ 94.25216265,  96.1248857 , 104.21807922, ...,  90.13664302,
          90.56435651,  89.1303442 ],
        [102.17370333, 104.21807922, 113.00682784, ...,  97.65879856,
          98.12424098,  96.56541676],
        ...,
        [ 88.40366275,  90.13664302,  97.65879856, ...,  89.58755222,
          90.06495771,  88.89617601],
        [ 88.81800922,  90.56435651,  98.12424098, ...,  90.06495771,
          90.60003819,  89.40220351],
        [ 87.41167664,  89.1303442 ,  96.56541676, ...,  88.89617601,
          89.40220351,  88.3053539 ]])

In [9]:
# using SVD to find eigen vector and eigen value

In [10]:
V, sigma, Ustar = svd(C)

sigma

array([3.96200979e+04, 3.23819227e+02, 5.44246465e+01, 2.63659524e+01,
       6.49692148e+00, 5.35518044e+00, 2.78064400e+00, 1.90980646e+00,
       1.22066270e+00, 5.91234064e-01, 4.11729904e-01, 3.09302148e-01,
       1.44537596e-01, 1.06471491e-01, 9.38944598e-02, 7.31527631e-02,
       5.99490781e-02, 5.08080067e-02, 3.68579806e-02, 3.01784273e-02,
       2.83707486e-02, 2.29002628e-02, 1.92678646e-02, 1.71941768e-02,
       1.47452830e-02, 1.23221324e-02, 1.17056848e-02, 1.05085860e-02,
       9.06665602e-03, 8.10857541e-03, 7.98117009e-03, 7.49965669e-03,
       6.91619322e-03, 6.47764764e-03, 6.24909839e-03, 5.81037484e-03,
       5.46489393e-03, 5.36486257e-03, 4.92147679e-03, 4.81367213e-03,
       4.57109462e-03, 4.49777538e-03, 4.11672008e-03, 3.98618322e-03,
       3.79799981e-03, 3.72653815e-03, 3.63114846e-03, 3.57403580e-03,
       3.37987290e-03, 3.29422615e-03, 3.18302628e-03, 3.02186165e-03,
       2.93759205e-03, 2.87624539e-03, 2.68916941e-03, 2.59943349e-03,
      

In [11]:
V = matrix (V)
V

matrix([[-4.80130114e-02, -3.46373789e-02, -8.17179631e-02, ...,
         -1.16816104e-02, -4.81311794e-04, -4.56885315e-04],
        [-4.89571914e-02, -3.59503675e-02, -8.98004363e-02, ...,
          7.11941447e-03,  2.41857313e-03, -8.81846607e-04],
        [-5.30674451e-02, -4.11646411e-02, -1.01255361e-01, ...,
          2.89337872e-02,  1.87016672e-04,  2.04803406e-03],
        ...,
        [-4.68738389e-02,  7.66398623e-02, -5.38040479e-02, ...,
         -5.88010231e-03, -9.65410763e-04,  5.83635857e-05],
        [-4.71082730e-02,  7.87584778e-02, -5.64996174e-02, ...,
         -1.90388928e-03,  1.12729606e-03, -1.46904702e-04],
        [-4.63733748e-02,  8.55738042e-02, -6.72817894e-02, ...,
          2.18927299e-03,  1.49226042e-03, -3.10061204e-04]])

In [12]:
Ustar = matrix(Ustar)
Ustar

matrix([[-4.80130114e-02, -4.89571914e-02, -5.30674451e-02, ...,
         -4.68738389e-02, -4.71082730e-02, -4.63733748e-02],
        [-3.46373789e-02, -3.59503675e-02, -4.11646411e-02, ...,
          7.66398623e-02,  7.87584778e-02,  8.55738042e-02],
        [-8.17179631e-02, -8.98004363e-02, -1.01255361e-01, ...,
         -5.38040479e-02, -5.64996174e-02, -6.72817894e-02],
        ...,
        [-1.16816102e-02,  7.11941375e-03,  2.89337873e-02, ...,
         -5.88010230e-03, -1.90388928e-03,  2.18927295e-03],
        [-4.81311653e-04,  2.41857243e-03,  1.87017381e-04, ...,
         -9.65410781e-04,  1.12729603e-03,  1.49226040e-03],
        [-4.56885441e-04, -8.81846471e-04,  2.04803478e-03, ...,
          5.83636196e-05, -1.46904704e-04, -3.10061188e-04]])

In [13]:
count = int(input('endmember : '))
count

endmember : 6


6

In [14]:
X = Ustar[:count]
X

matrix([[-0.04801301, -0.04895719, -0.05306745, ..., -0.04687384,
         -0.04710827, -0.04637337],
        [-0.03463738, -0.03595037, -0.04116464, ...,  0.07663986,
          0.07875848,  0.0855738 ],
        [-0.08171796, -0.08980044, -0.10125536, ..., -0.05380405,
         -0.05649962, -0.06728179],
        [-0.055966  , -0.05829666, -0.06274655, ...,  0.11650537,
          0.11312166,  0.10298599],
        [-0.05729587, -0.03914948, -0.02929549, ..., -0.01047926,
          0.03765945,  0.00832081],
        [-0.12656048, -0.13760931, -0.15175598, ..., -0.06503422,
         -0.04993157, -0.05729765]])

In [15]:
Y = V[:,:count]
Y

matrix([[-0.04801301, -0.03463738, -0.08171796, -0.055966  , -0.05729587,
         -0.12656048],
        [-0.04895719, -0.03595037, -0.08980044, -0.05829666, -0.03914948,
         -0.13760931],
        [-0.05306745, -0.04116464, -0.10125536, -0.06274655, -0.02929549,
         -0.15175598],
        ...,
        [-0.04687384,  0.07663986, -0.05380405,  0.11650537, -0.01047926,
         -0.06503422],
        [-0.04710827,  0.07875848, -0.05649962,  0.11312166,  0.03765945,
         -0.04993157],
        [-0.04637337,  0.0855738 , -0.06728179,  0.10298599,  0.00832081,
         -0.05729765]])

In [16]:
Z = diag(sigma[:count])
Z

array([[3.96200979e+04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 3.23819227e+02, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.44246465e+01, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.63659524e+01,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        6.49692148e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 5.35518044e+00]])

In [17]:
np.dot(np.dot(Y,Z),X)

matrix([[ 92.27582972,  94.12677049, 102.06754089, ...,  88.4229196 ,
          88.83394212,  87.43834055],
        [ 94.12677049,  96.02008158, 104.12413845, ...,  90.16293553,
          90.58800252,  89.16435454],
        [102.06754089, 104.12413845, 112.91571482, ...,  97.69100206,
          98.1546843 ,  96.60644244],
        ...,
        [ 88.4229196 ,  90.16293553,  97.69100206, ...,  89.49236721,
          89.96928633,  88.77861353],
        [ 88.83394212,  90.58800252,  98.1546843 , ...,  89.96928633,
          90.46681076,  89.26670219],
        [ 87.43834055,  89.16435454,  96.60644244, ...,  88.77861353,
          89.26670219,  88.11795103]])

In [18]:
C

matrix([[ 92.45696969,  94.25216265, 102.17370333, ...,  88.40366275,
          88.81800922,  87.41167664],
        [ 94.25216265,  96.1248857 , 104.21807922, ...,  90.13664302,
          90.56435651,  89.1303442 ],
        [102.17370333, 104.21807922, 113.00682784, ...,  97.65879856,
          98.12424098,  96.56541676],
        ...,
        [ 88.40366275,  90.13664302,  97.65879856, ...,  89.58755222,
          90.06495771,  88.89617601],
        [ 88.81800922,  90.56435651,  98.12424098, ...,  90.06495771,
          90.60003819,  89.40220351],
        [ 87.41167664,  89.1303442 ,  96.56541676, ...,  88.89617601,
          89.40220351,  88.3053539 ]])

In [19]:
# eigen vectors Y(coloumn wise) and accordingly eigen values (diagonally):

In [20]:
Y

matrix([[-0.04801301, -0.03463738, -0.08171796, -0.055966  , -0.05729587,
         -0.12656048],
        [-0.04895719, -0.03595037, -0.08980044, -0.05829666, -0.03914948,
         -0.13760931],
        [-0.05306745, -0.04116464, -0.10125536, -0.06274655, -0.02929549,
         -0.15175598],
        ...,
        [-0.04687384,  0.07663986, -0.05380405,  0.11650537, -0.01047926,
         -0.06503422],
        [-0.04710827,  0.07875848, -0.05649962,  0.11312166,  0.03765945,
         -0.04993157],
        [-0.04637337,  0.0855738 , -0.06728179,  0.10298599,  0.00832081,
         -0.05729765]])

In [21]:
M = -1*Y
M

matrix([[ 0.04801301,  0.03463738,  0.08171796,  0.055966  ,  0.05729587,
          0.12656048],
        [ 0.04895719,  0.03595037,  0.08980044,  0.05829666,  0.03914948,
          0.13760931],
        [ 0.05306745,  0.04116464,  0.10125536,  0.06274655,  0.02929549,
          0.15175598],
        ...,
        [ 0.04687384, -0.07663986,  0.05380405, -0.11650537,  0.01047926,
          0.06503422],
        [ 0.04710827, -0.07875848,  0.05649962, -0.11312166, -0.03765945,
          0.04993157],
        [ 0.04637337, -0.0855738 ,  0.06728179, -0.10298599, -0.00832081,
          0.05729765]])

In [22]:
Z

array([[3.96200979e+04, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 3.23819227e+02, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 5.44246465e+01, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 2.63659524e+01,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        6.49692148e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 5.35518044e+00]])

In [23]:
#To find the abundance:[P1, P2, P3]np.transpose[1, a1, a2] = Pa >= 0:

In [24]:
import random
M



matrix([[ 0.04801301,  0.03463738,  0.08171796,  0.055966  ,  0.05729587,
          0.12656048],
        [ 0.04895719,  0.03595037,  0.08980044,  0.05829666,  0.03914948,
          0.13760931],
        [ 0.05306745,  0.04116464,  0.10125536,  0.06274655,  0.02929549,
          0.15175598],
        ...,
        [ 0.04687384, -0.07663986,  0.05380405, -0.11650537,  0.01047926,
          0.06503422],
        [ 0.04710827, -0.07875848,  0.05649962, -0.11312166, -0.03765945,
          0.04993157],
        [ 0.04637337, -0.0855738 ,  0.06728179, -0.10298599, -0.00832081,
          0.05729765]])

In [27]:
from random import *
t=0
Afinal=matrix([0,0,0,0,0])
while(t<5):
    Pset=[]
    i=0
   # u=0
    Pset=sample(range(0,168),5)
    f=matrix([0,0,0,0,0,0])
    for i in Pset:
        f=vstack((f,M[i-1:i,:]))
    f=f[1:]
    f1=f[:,1:]
    f1
    z=f[:,:1]
    If1=linalg.pinv(f1)
    q=If1.dot(z)
    o=matrix([[1],[q[0,0]],[q[1,0]],[q[2,0]],[q[3,0]],[q[4,0]]])
    K=M.dot(o)
    flag=1
    for i in K:
        if(i<0):
            flag=0
            break
    #u=count_nonzero(K)
    #if(u!=162):
        #flag=0
    if(flag==1):
        t=t+1
        q=transpose(q)
        Afinal=vstack((Afinal,q[:,:]))
Afinal=Afinal[1:,:]
Afinal

matrix([[-0.36831564,  0.52390263,  0.12389672,  0.12633019,  0.02991489],
        [ 0.22021683,  0.29926684, -0.42868126,  0.08573658, -0.28442037],
        [-0.61150962,  0.13390871, -0.14285606, -0.15953528, -0.14294299],
        [-0.30409372,  0.45664907, -0.13397004, -0.19844119,  0.19328232],
        [-0.70117249, -0.0720785 ,  0.00791206, -0.2013491 , -0.00182562]])